### ISSUE TITLE
Reports marked as public not available to Everyone

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_reportit#46]
If you navigate to console-->reports->Click edit report and mark it as public hit save:

![image](https://user-images.githubusercontent.com/11211789/45928456-fcb6fc80-bf11-11e8-81c8-66551fd189e3.png)

Then from report filter same report shows as NOT public:.
This issue result in situation that only owner can see a report that was marked as Public
![image](https://user-images.githubusercontent.com/11211789/45928482-6800ce80-bf12-11e8-9ffb-16d646f543f7.png)

**Comment by netniV** [comment]
This sounds like the save is actually failing, anything in the logs?

**Comment by netniV** [comment]
I think you'll find that in plugin_reporit_reports the report doesn't have a value in the public column.

**Comment by ikorzha** [comment]
There is nothing in the logs. I have looked at table: plugin_reporit_reports and it does have value of 1 for publish and value of 1 for scheduled.
However both of these fields on reporting page show as "no"

See screenshot attached:
I am also attaching an sql export of that table, feel free to import it into your db for testing:
[plugin_reportit_reports.txt](https://github.com/Cacti/plugin_reportit/files/2409001/plugin_reportit_reports.txt)


![image](https://user-images.githubusercontent.com/11211789/45931452-559b8a80-bf3c-11e8-9ab2-56014387df91.png)

**Comment by netniV** [comment]
1? That sounds wrong because it should be '' (off/false) or 'on' (on/true)

**Comment by netniV** [comment]
@ikorzha Can you download the latest dev version and try again?  I'm sure this is corrected now.

**Comment by ikorzha** [comment]
Unfortunately I have to state that it is not corrected.
My steps: Console ->Reports->"Click on the actual report"-> See screenshot below:
As you can see public check-mark is present and saved.
![image](https://user-images.githubusercontent.com/11211789/46252164-16d16d00-c433-11e8-85ea-f3bd287fcc10.png)

However on reports screen on console no checkmark is present, there is a disconnect between these 2 fields:
![image](https://user-images.githubusercontent.com/11211789/46252194-7760aa00-c433-11e8-8acf-1d098f8c58e8.png)
_________________________________________________________________________________________________________
Additionally I want to mention that report saving doesn't honor any setting "saves" to scheduling portion of report:
![image](https://user-images.githubusercontent.com/11211789/46252241-2604ea80-c434-11e8-8890-3710afa6ec37.png)

**Comment by netniV** [comment]
Any errors in the logs?

**Comment by netniV** [comment]
So, your import says that the report is public:
![image](https://user-images.githubusercontent.com/9052188/46255730-d3a9e500-c498-11e8-943b-f23c7d1ecdbc.png)

All I did was keep just the INSERT INTO line, remove everything on that line upto and include the first bracket, then put a new line after the closing bracket and remove that, plus the "VALUS" text and opening bracket.  Then removed the closing bracket and semi colon and then replace all the backticks(`) that were left with single quotes.

This leaves you with a CSV importable file, which I loaded into Numbers on my Mac to get the above screenshot. So, now the question is, why does your import think it's public but not public.

**Comment by netniV** [comment]
So more changes have been pushed.  Saving should now work for reports.

**Comment by ikorzha** [comment]
You are making process here: Report when now marked as public retain their properties:
This issue resolved.
![image](https://user-images.githubusercontent.com/11211789/46257592-60997200-c48a-11e8-90b5-e60ae9e11be6.png)

Changes to scheduled items still do not get saved:
![image](https://user-images.githubusercontent.com/11211789/46257601-8aeb2f80-c48a-11e8-98b7-505b220ce9e2.png)

**Comment by ikorzha** [comment]
netniV, here is animated gif to demonstrate the issue with saving of "scheduling reporting"
![scheduling-not-working](https://user-images.githubusercontent.com/11211789/46257798-faaee980-c48d-11e8-8ed2-e620ce702827.gif)

**Comment by netniV** [comment]
I have an update shortly, that should hopefully resolve half of this.

**Comment by netniV** [comment]
It's part of a larger issue #53

**Comment by netniV** [comment]
Scheduling is also under #24 so I'm going to close this for now.
